kind: Service
apiVersion: v1
metadata:
  name: chuckhinson-g
  labels:
    net.beedemo.deploy.type: workshop
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: chuckhinson-g
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: chuckhinson-g-staging
  labels:
    net.beedemo.deploy.type: workshop
spec:
  replicas: 1
  template:
    metadata:
      name: chuckhinson-g
      labels:
        net.beedemo.deploy.type: workshop
        app: chuckhinson-g
        env: staging
    spec:
      serviceAccountName: cjoc
      containers:
      - name: chuckhinson-g
        image: gcr.io/core-workshop/helloworld-nodejs:chuckhinson-g-3
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
        imagePullPolicy: Always
        ports:
        - name: public
          containerPort: 8080
      securityContext:
        runAsUser: 1000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chuckhinson-g
  labels:
    net.beedemo.deploy.type: workshop
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /chuckhinson-g/?(.*)
        backend:
          serviceName: chuckhinson-g
          servicePort: 80
    host: staging.cb-sa.io
